### ISSUE TITLE
Changing Email Address not working

### ISSUE THREAD

**Issue by andrumatt** [Playabl-io/playabl#157]
**Describe the bug**
I am unable to change my email address. I am trying to change my email address because I am not receiving the emails from event organizers who are confirming attendance for the game. 

**To Reproduce**
1. Go to https://app.playabl.io/profile.
2. Enter a new email address into Email field.
3. Click Update button at the bottom of the page.
4. I get two messages: 
     a. At the bottom of the screen is a blue bar that says: "Email change registered. Please confirm by following the link sent to the new email." I do not receive any message at my old or new email address.
     b. After the bubbles stop in the Update button, at the top of the screen is a message in a pink box: "That's not right. Something went wrong" with no other info.

**Expected behavior**
I expect the blue bar to be correct. To receive an confirmation email at the new address that will contain I link I can click on and confirm the email address change.

**Desktop (please complete the following information):**
 - OS: macOS 13.5.1
 - Browser Safari 
 - Version 16.6

**Comment by jongrim** [comment]
Hi! Just commenting really quick to acknowledge this since it's been a few weeks. I really thought I'd get an email if someone filed a bug but alas, I did not and just now noticed it. Sorry!

I've had suspicions this might not be working, so I will dig into it ASAP. I'll try to comment back within a week with an update on findings or progress, if not an outright fix.

**Comment by jongrim** [comment]
Hey @andrumatt I'm happy to report this should be fixed! After close review I found there was a misconfiguration in the SMTP settings and after adjusting, things worked as expected for me to change my email. Please do give it a try and let me know if you still have any issues!

**Comment by andrumatt** [comment]
Yes, I was successfully able to change my email address, so it appears to be working as expected now. Thanks!
