### ISSUE TITLE
Games still show on event  pages even when cancelled

### ISSUE THREAD

**Issue by GKumquat** [Playabl-io/playabl#242]
**Describe the bug**
Games that were cancelled still show on event pages after cancellation. They are not visible anywhere else. 

**To Reproduce**

1. Create and event
2. create a game under that event
3. cancel the game
4. the game is still listed under the event, but nowhere else

**Expected behavior**
I would expect the game not to be listed under the even 

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu or Windows 11
- Browser: Firefox

**Smartphone (please complete the following information):**

- OS: LineagOS
- Browser: Firefox

**Comment by jongrim** [comment]
Thanks! Indeed I'd missed adding the constraint check to filter out canceled games but that should be fixed now!
