### ISSUE TITLE
Cannot change "how to join" in a community 

### ISSUE THREAD

**Issue by GKumquat** [Playabl-io/playabl#244]
**Describe the bug**
Currently there is no way to change the description in the  "How to join" section  on the community page.  

**Expected behavior**
An option to change this text in the manage section.

**Desktop (please complete the following information):**

- OS: Ubuntu/Win 11
- Browser: Firefox

**Smartphone (please complete the following information):**

- OS: LineageOS
- Browser: Firefox

**Comment by jongrim** [comment]
Added this to the Manage -> Info -> Community Info section so you should be able to update it now! Added in #245
