### ISSUE TITLE
Add ability to open all calendar links at once

### ISSUE THREAD

**Issue by jongrim** [Playabl-io/playabl#255]
**Is your feature request related to a problem? Please describe.**
Right now you have to individually click each google calendar link to add the session to your calendar. This is tedious.

**Describe the solution you'd like**
The best solution is a full google integration, but that is time consuming and more involved.

**Describe alternatives you've considered**
Alternatively, a user action to be able to open all of the google cal links at once in new tabs saves some clicks, and the user will only have to visit each tab to complete saving. This may introduce a risk of people missing saving a calendar item though, since the number of tabs could be large and it is easy as humans to get distracted.

**Additional context**

**Comment by AnukratiMehta** [comment]
@jongrim, I'd like to give this a try.

**Comment by jongrim** [comment]
@AnukratiMehta that would be great! I need to finish figuring out how exactly other can run the project locally, so I will do that this weekend. Give me a few days and I'll comment back with some guidance on how to get started and where to look for this. Thanks!

**Comment by jongrim** [comment]
Hey - so sorry I'm so late coming back to you. I was going to say though that I don't think this needs to be done any longer. This was a sort-of hacky way to help people add items to their calendar, but then I stumbled on the webcal idea and that is a much better way for people to keep their calendars in sync. I'm going to close this one now as I don't think we still need this work. Thank you for your interest in helping out - if you see any other issues or have other ideas, you're welcome to contribute!
